### ISSUE TITLE
missing assets in the environment

### ISSUE THREAD

**Issue by WeiChengTseng** [kennyderek/adap#1]
Hi! Thanks for sharing this cool project.

Recently, we would like to reproduce the results of this work, and I ran
`python run.py --conf ../configs/cartpole/train/adap.yaml --exp-name cartpole`

Then, I got the error shown below.
```
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from common import get_env_and_callbacks, get_name_creator, get_trainer, build_trainer_config, get_name_creator
  File "/media/champagne/ethan/adap/scripts/common.py", line 2, in <module>
    from adapenvs.farmworld.farmworld import Farmworld
  File "/media/champagne/ethan/adap/adaptation_envs/adapenvs/farmworld/farmworld.py", line 12, in <module>
    from adapenvs.farmworld.agent import Agent
  File "/media/champagne/ethan/adap/adaptation_envs/adapenvs/farmworld/agent.py", line 12, in <module>
    class Agent(Unit):
  File "/media/champagne/ethan/adap/adaptation_envs/adapenvs/farmworld/agent.py", line 21, in Agent
    sword = np.array(Image.open(get_resource_path("sword.png")))
  File "/home/ethan/anaconda3/envs/adap/lib/python3.8/site-packages/PIL/Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/media/champagne/ethan/adap/adaptation_envs/adapenvs/farmworld/resources/sword.png'
```

It seems that some assets are missing in this repo. Can you add those assets to the repo as well?

**Comment by kennyderek** [comment]
Thanks for bringing this to my attention, glad you are interested in the project! For now I have removed these missing dependencies - hopefully it runs, but I know that the underlying Rllib has also changed since I posted this code. By tonight I'll try to put up a more comprehensive fix, including the Farmworld dependencies so you can work on that env.

**Comment by WeiChengTseng** [comment]
Thanks for the quick response, and I am looking forward to your further update 😄.

**Comment by WeiChengTseng** [comment]
May I roughly know when the environment (Farmworld) will be included? I am looking forward to your updates. Thanks a lot.

**Comment by kennyderek** [comment]
Apologies for the delays, I expect one or two more days. If you want, there is code in the `add_farm` branch that should allow you to run things with Farmworld right now. The `run.py` script is slightly modified so it does not exactly coincide with the README.md, but you can just look at the code to see what cmd arguments need to be.

The main part I'm working on is getting a decent environment wrapper/interface that that allows you to adapt latent codes to fit ablations in an environment-agnostic(ish) manner - the code I was using before was very hacky into the environments themselves (so it didn't allow you to swap/experiment on your own envs). In the meantime, were you able to get it working with CartPole?

**Comment by WeiChengTseng** [comment]
Thanks for your effort in making the repo. complete. I am able to work with CartPole, and the results seem to be reasonable. Although the underlying Rllib has also changed, it seems that it doesn't cause any issue for your code 😄.
